# Generated by Django 4.2.6 on 2023-10-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsDetails',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=50, null=True)),
                ('ProductName', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=5000)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('Category', models.CharField(max_length=500)),
                ('CompanyName', models.CharField(max_length=500, null=True)),
                ('ProductImage', models.ImageField(upload_to='product_images/')),
                ('AddedTime', models.DateTimeField(auto_now_add=True)),
                ('ModifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
