# Generated by Django 4.2.6 on 2023-10-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCartDetails',
            fields=[
                ('CartId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('ProductId', models.CharField(max_length=500)),
                ('ProductName', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=5000)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('TotalQuantity', models.IntegerField()),
                ('Category', models.CharField(max_length=500)),
                ('CompanyName', models.CharField(max_length=500, null=True)),
                ('CartProductAddedTime', models.DateTimeField(auto_now_add=True)),
                ('CartProductModifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
