# Generated by Django 4.2.6 on 2023-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0002_productcartdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBuyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackingId', models.CharField(max_length=50)),
                ('UserId', models.CharField(max_length=50)),
                ('ProductIds', models.CharField(max_length=100, null=True)),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('TotalQuantity', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=6)),
                ('ProductTrackingStatus', models.CharField(max_length=255)),
                ('OrderConfirm', models.IntegerField(default=0)),
                ('BuyProductAddedTime', models.DateTimeField(auto_now_add=True)),
                ('BuyProductModifiedTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
