# Generated by Django 4.2.6 on 2023-10-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0003_productbuydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfirmDetails',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=50)),
                ('TrackingId', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=100)),
                ('Otp', models.IntegerField(null=True)),
                ('OrderAddedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
