# Generated by Django 4.2.6 on 2023-10-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0006_remove_productbuydetails_productids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductId',
            field=models.CharField(max_length=100),
        ),
    ]
