# Generated by Django 4.2.6 on 2023-10-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0007_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmdetails',
            name='Otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
