# Generated by Django 4.2.6 on 2023-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_shop', '0009_remove_orderconfirmdetails_productids_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderConfirmDetails',
        ),
        migrations.AddField(
            model_name='productbuydetails',
            name='Otp',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
